INSERT INTO record (record_id, catalog_number, artists, album_title, track_artists, song_titles, release_date, title_version, genre) VALUES 
 (1,'SW001','Samoan Attorney','We Were Somewhere Around Barstow','Samoan Attorney','We Were Somewhere Around Barstow','9/5/2001','Original Mix','Electronic - Techno'),
 (2,'SW001','Samoan Attorney','We Were Somewhere Around Barstow','Samoan Attorney','We Were Somewhere Around Barstow (L.A. Williams'' Chicago Whoop Azz DJ Mixx)','9/5/2001','L.A. Williams'' Chicago Whoop Azz DJ Mixx','Electronic - Techno'),
 (3,'SW002','The Diamond Dogs','The Conception EP','The Diamond Dogs','Velvet Driveshaft','11/19/2002','Original Mix','Electronic - Techno'),
 (4,'SW002','The Diamond Dogs','The Conception EP','The Diamond Dogs','The Beater','11/19/2002','Original Mix','Electronic - Techno'),
 (5,'SW002','The Diamond Dogs','The Conception EP','The Diamond Dogs','Jak Stat','11/19/2002','Original Mix','Electronic - Techno'),
 (6,'SW003','The Attorney General','The Great Lakes Sound EP','The Attorney General','Jack In Space','4/19/2003','Original Mix','Electronic - Techno'),
 (7,'SW003','The Attorney General','The Great Lakes Sound EP','The Attorney General','Jack In Space Hands Gruber Remix','4/19/2003','Hands Gruber Remix','Electronic - Techno'),
 (8,'SW003','The Attorney General','The Great Lakes Sound EP','The Attorney General','Ignition','4/19/2003','Original Mix','Electronic - Techno'),
 (9,'SW004','pan/tone','The Smut Peddler','pan/tone','Danke Streak Appeal','6/8/2004','Original Mix','Electronic - Techno'),
 (10,'SW004','pan/tone','The Smut Peddler','pan/tone','Dirt Bag','6/8/2004','Original Mix','Electronic - Techno'),
 (11,'SW004','pan/tone','The Smut Peddler','pan/tone','Smut','6/8/2004','Original Mix','Electronic - Techno'),
 (12,'SW005','German Broadcasters','Activate EP','German Broadcasters','Activate','9/29/2005','Original Mix','Electronic - Techno'),
 (13,'SW005','German Broadcasters','Activate EP','German Broadcasters','Repeat (Feat. Adamin 80)','9/29/2005','Original Mix','Electronic - Techno'),
 (14,'SW005','German Broadcasters','Activate EP','German Broadcasters','I Machine','9/29/2005','Original Mix','Electronic - Electro House'),
 (15,'SW006','Greg Kobe','The Putana EP','Greg Kobe','Dirty Putana','1/26/2006','Original Mix','Electronic - Techno'),
 (16,'SW006','Greg Kobe','The Putana EP','Greg Kobe','Life of Agony','1/26/2006','Original Mix','Electronic - Techno'),
 (17,'SW006','Greg Kobe','The Putana EP','Greg Kobe','New Religion','1/26/2006','Original Mix','Electronic - Techno'),
 (18,'SW007','Chriss Zimmer','The Sympatico EP','Chriss Zimmer','Kama','3/2/2006','Original Mix','Electronic - Techno'),
 (19,'SW007','Chriss Zimmer','The Sympatico EP','Chriss Zimmer','Himen','3/2/2006','Original Mix','Electronic - Techno'),
 (20,'SW007','Chriss Zimmer','The Sympatico EP','Chriss Zimmer','Himen2','3/2/2006','Original Mix','Electronic - Techno'),
 (21,'SW008','Sascha Muller','Wheels of Steel EP','Sascha Muller','Stahlplatten','3/16/2006','Original Mix','Electronic - Techno'),
 (22,'SW008','Sascha Muller','Wheels of Steel EP','Sascha Muller','Hell''s Bells','3/16/2006','Original Mix','Electronic - Techno'),
 (23,'SW009','Mark Thibideau','The Conclusion EP','Mark Thibideau','Friction','5/9/2006','Original Mix','Electronic - Techno'),
 (24,'SW009','Mark Thibideau','The Conclusion EP','Mark Thibideau','Separation Process','5/9/2006','Original Mix','Electronic - Techno'),
 (25,'SW010','Rafael Araujo','The Galera EP','Rafael Araujo|B-Vision|B. Hilgemberg','Galera','7/20/2006','Original Mix','Electronic - Electro House'),
 (26,'SW010','Rafael Araujo','The Galera EP','Rafael Araujo|B. Hilgemberg','Mandagua','7/20/2006','Original Mix','Electronic - Electro House'),
 (27,'SW011','Chriss Zimmer','The Aural Pleasures EP','Chriss Zimmer','Dictionary','9/14/2006','Original Mix','Electronic - Electro House'),
 (28,'SW011','Chriss Zimmer','The Aural Pleasures EP','Chriss Zimmer','Don''t Panic','9/14/2006','Original Mix','Electronic - Electro House'),
 (29,'SW011','Chriss Zimmer','The Aural Pleasures EP','Chriss Zimmer','Mo-nik','9/14/2006','Original Mix','Electronic - Electro House'),
 (30,'SW011','Chriss Zimmer','The Aural Pleasures EP','Chriss Zimmer','Nunes','9/14/2006','Original Mix','Electronic - Electro House'),
 (31,'SW012','Sascha Muller','The Bunker EP','Sascha Muller','Bunker','10/10/2006','Original Mix','Electronic - Techno'),
 (32,'SW012','Sascha Muller','The Bunker EP','Sascha Muller','Base Raper','10/10/2006','Original Mix','Electronic - Techno'),
 (33,'SW012','Sascha Muller','The Bunker EP','Sascha Muller','Dave','10/10/2006','Original Mix','Electronic - Techno'),
 (34,'SW013','Tonske','The Fact Noises EP','Tonske','Fact Noises','11/2/2006','Original Mix','Electronic - Techno'),
 (35,'SW013','Tonske','The Fact Noises EP','Tonske','Heavy Sticks','11/2/2006','Original Mix','Electronic - Tech House'),
 (36,'SW013','Tonske','The Fact Noises EP','Tonske','Toronto Area','11/2/2006','Original Mix','Electronic - Tech House'),
 (37,'SW014','Mark Quail','Frostbite','Mark Quail','Frostbite','11/16/2006','Original Mix','Electronic - Tech House'),
 (38,'SW014','Mark Quail','Frostbite','Mark Quail','Frostbite Arthur Oskan Remix','11/16/2006','Arthur Oskan Remix','Electronic - Tech House'),
 (39,'SW015','Chriss Zimmer','Clubbing Life in Crocov','Chriss Zimmer','Crazy Drummer','12/7/2006','Original Mix','Electronic - Electro House'),
 (40,'SW015','Chriss Zimmer','Clubbing Life in Crocov','Chriss Zimmer','Bursztyn','12/7/2006','Original Mix','Electronic - Electro House'),
 (41,'SW015','Chriss Zimmer','Clubbing Life in Crocov','Chriss Zimmer','7th Heaven','12/7/2006','Original Mix','Electronic - Electro House'),
 (42,'SW016','Bruno Balbino','The Estemesmo EP','Bruno Balbino','Estemesmo','12/21/2006','Original Mix','Electronic - Tech House'),
 (43,'SW016','Bruno Balbino','The Estemesmo EP','Bruno Balbino','Truth Zone','12/21/2006','Original Mix','Electronic - House'),
 (44,'SW016','Bruno Balbino','The Estemesmo EP','Bruno Balbino','Get Lost','12/21/2006','Original Mix','Electronic - House'),
 (45,'SW017','Chriss Zimmer','The Rombaro EP','Chriss Zimmer','Guss Roboter','2/22/2007','Original Mix','Electronic - Electro House'),
 (46,'SW017','Chriss Zimmer','The Rombaro EP','Chriss Zimmer','Perversionen Forte Brincal','2/22/2007','Original Mix','Electronic - Electro House'),
 (47,'SW017','Chriss Zimmer','The Rombaro EP','Chriss Zimmer','Operators','2/22/2007','Original Mix','Electronic - Electro House'),
 (48,'SW018','DJ Soma Cruz','Luxure','DJ Soma Cruz','Luxure','4/19/2007','Original Mix','Electronic - Minimal'),
 (49,'SW018','DJ Soma Cruz','Luxure','DJ Soma Cruz','Luxure Chriss Zimmer Remix','4/19/2007','Chriss Zimmer Remix','Electronic - Minimal'),
 (50,'SW019','Symplx','The Variance EP','Symplx','The Return to 1484','5/17/2007','Original Mix','Electronic - Techno'),
 (51,'SW019','Symplx','The Variance EP','Symplx','Body Control','5/17/2007','Original Mix','Electronic - Tech House'),
 (52,'SW019','Symplx','The Variance EP','Symplx','Make The Jack Jak','5/17/2007','Original Mix','Electronic - Tech House'),
 (53,'SW019','Symplx','The Variance EP','Symplx','The Last Laugh','5/17/2007','Original Mix','Electronic - Tech House'),
 (54,'SW019','Symplx','The Variance EP','Symplx','The Sorcerer Userwave Remix','5/17/2007','Userwave Remix','Electronic'),
 (55,'SW019','Symplx','The Variance EP','Symplx','The More Things Change','5/17/2007','Original Mix','Electronic - Techno'),
 (56,'SW020','Gianluca Luisi','The Loneliness EP','Gianluca Luisi','Holdetune','6/13/2007','Original Mix','Electronic - Minimal'),
 (57,'SW020','Gianluca Luisi','The Loneliness EP','Gianluca Luisi','Antirrobo','6/13/2007','Original Mix','Electronic - Minimal'),
 (58,'SW020','Gianluca Luisi','The Loneliness EP','Gianluca Luisi','Fixed Velocity','6/13/2007','Original Mix','Electronic - Minimal'),
 (59,'SW021','Sascha Muller','Another Level EP','Sascha Muller','On A Mission','7/26/2007','Original Mix','Electronic - Techno'),
 (60,'SW021','Sascha Muller','Another Level EP','Sascha Muller','Saigon','7/26/2007','Original Mix','Electronic - Techno'),
 (61,'SW021','Sascha Muller','Another Level EP','Sascha Muller','UFO','7/26/2007','Original Mix','Electronic - Techno'),
 (62,'SW022','DJ Soma Cruz','Glam','DJ Soma Cruz','Glam','9/21/2007','Original Mix','Electronic - Tech House'),
 (63,'SW022','DJ Soma Cruz','Glam','DJ Soma Cruz','Glam Noah Pred Remix','9/21/2007','Noah Pred Remix','Electronic - Minimal'),
 (64,'SW023','Better Than Raw','Livebox EP','Better Than Raw','Livebox','11/16/2007','Original Mix','Electronic - Electro House'),
 (65,'SW023','Better Than Raw','Livebox EP','Better Than Raw','Salo','11/16/2007','Original Mix','Electronic - Techno'),
 (66,'SW024','Userwave','The Illuminated Night EP','Userwave','Pan Human','1/31/2008','Original Mix','Electronic - Techno'),
 (67,'SW024','Userwave','The Illuminated Night EP','Userwave','Ontocentrism','1/31/2008','Original Mix','Electronic - Techno'),
 (68,'SW024','Userwave','The Illuminated Night EP','Userwave','Algernon','1/31/2008','Original Mix','Electronic - Techno'),
 (69,'SW024','Userwave','The Illuminated Night EP','Userwave','Perfect Historianism','1/31/2008','Original Mix','Electronic - Techno'),
 (70,'SW025','Cozmic Spore','The Night Out EP','Cozmic Spore','Take A Pill','2/20/2008','Original Mix','Electronic - Techno'),
 (71,'SW025','Cozmic Spore','The Night Out EP','Cozmic Spore','Altered Beast','2/20/2008','Original Mix','Electronic - Techno'),
 (72,'SW025','Cozmic Spore','The Night Out EP','Cozmic Spore','Mellow Out','2/20/2008','Original Mix','Electronic - Techno'),
 (73,'SW025','Cozmic Spore','The Night Out EP','Cozmic Spore','Waking Up','2/20/2008','Original Mix','Electronic - Techno'),
 (74,'SW026','Symplx','Lost Planet Tracks Volume 1','Symplx','Defcon Serenade','3/7/2008','Original Mix','Electronic - Techno'),
 (75,'SW026','Symplx','Lost Planet Tracks Volume 1','Symplx','Pimpin'' & Pushin''','3/7/2008','Original Mix','Electronic - Tech House'),
 (76,'SW026','Symplx','Lost Planet Tracks Volume 1','Symplx','Touched By An Android','3/7/2008','Original Mix','Electronic - Techno'),
 (77,'SW026','Symplx','Lost Planet Tracks Volume 1','Symplx','Twister','3/7/2008','Original Mix','Electronic - Techno'),
 (78,'SW027','Vandermeer|Nitin','Don''t Feed The Ghosts EP','Vandermeer|Nitin','Beached Beluga','3/21/2008','Original Mix','Electronic - Techno'),
 (79,'SW027','Vandermeer|Nitin','Don''t Feed The Ghosts EP','Vandermeer|Nitin','Hungry Ghosts','3/21/2008','Original Mix','Electronic - Techno'),
 (80,'SW028','Repair','Lines Drawn','Repair','Lines Drawn','5/22/2008','Original Mix','Electronic - Deep House'),
 (81,'SW028','Repair','Lines Drawn','Repair','Lines Drawn Matt Thibideau Remix','5/22/2008','Matt Thibideau Remix','Electronic - Tech House'),
 (82,'SW028','Repair','Lines Drawn','Repair','On Hold','5/22/2008','Original Mix','Electronic - Tech House'),
 (83,'SW028','Repair','Lines Drawn','Repair','Seven Sisters Electric Plant','5/22/2008','Original Mix','Electronic - Techno'),
 (84,'SW029','Curtis|Estrada','Doesn''t Matter','Curtis|Estrada','Doesn''t Matter','6/17/2008','Original Mix','Electronic - Tech House'),
 (85,'SW029','Curtis|Estrada','Doesn''t Matter','Curtis|Estrada','Doesn''t Matter Nerone Remix','6/17/2008','Nerone Remix','Electronic - Tech House'),
 (86,'SW030','Caspian Rabone','The Plain Truth','Caspian Rabone','Plain Truth','9/25/2008','Original Mix','Electronic - Techno'),
 (87,'SW030','Caspian Rabone','The Plain Truth','Caspian Rabone','The Calm','9/25/2008','Original Mix','Electronic - Techno'),
 (88,'SW031','Vandermeer|Nitin','Speak Slowly EP','Vandermeer','Leggo My Ego','12/10/2008','Original Mix','Electronic - Techno'),
 (89,'SW031','Vandermeer|Nitin','Speak Slowly EP','Nitin','Speak Slowly Please','12/10/2008','Original Mix','Electronic - Techno'),
 (90,'SW032','Rodrigo Diaz','Aliens On The Trees EP','Rodrigo Diaz','The Aliens','2/12/2009','Original Mix','Electronic - Tech House'),
 (91,'SW032','Rodrigo Diaz','Aliens On The Trees EP','Rodrigo Diaz','Trees','2/12/2009','Original Mix','Electronic - Tech House'),
 (92,'SW033','Various','Canadian High Grade Techno','Caspian Rabone','Plain Truth','3/19/2009','Original Mix','Electronic - Techno'),
 (93,'SW033','Various','Canadian High Grade Techno','Mark Thibideau','Separation Process','3/19/2009','Original Mix','Electronic - Techno'),
 (94,'SW033','Various','Canadian High Grade Techno','The Attorney General','Ignition','3/19/2009','Original Mix','Electronic - Techno'),
 (95,'SW033','Various','Canadian High Grade Techno','pan/tone','Dirt Bag','3/19/2009','Original Mix','Electronic - Techno'),
 (96,'SW033','Various','Canadian High Grade Techno','Vandermeer|Nitin','Hungry Ghosts','3/19/2009','Original Mix','Electronic - Techno'),
 (97,'SW033','Various','Canadian High Grade Techno','Symplx','The Return to 1484','3/19/2009','Original Mix','Electronic - Techno'),
 (98,'SW033','Various','Canadian High Grade Techno','The Diamond Dogs','Velvet Driveshaft','3/19/2009','Original Mix','Electronic - Techno'),
 (99,'SW033','Various','Canadian High Grade Techno','Userwave','Pan Human','3/19/2009','Original Mix','Electronic - Techno'),
 (100,'SW033','Various','Canadian High Grade Techno','The Attorney General','Jack In Space Hands Gruber Remix','3/19/2009','Hands Gruber Remix','Electronic - Techno'),
 (101,'SW033','Various','Canadian High Grade Techno','Mark Quail','Frostbite Arthur Oskan Remix','3/19/2009','Arthur Oskan Remix','Electronic - Tech House'),
 (102,'SW033','Various','Canadian High Grade Techno','Repair','Lines Drawn Matt Thibideau Remix','3/19/2009','Matt Thibideau Remix','Electronic - Tech House'),
 (103,'SW034','Curtis|Estrada','The Influence EP','Curtis|Estrada','Africa Brass','6/10/2009','Original Mix','Electronic - Tech House'),
 (104,'SW034','Curtis|Estrada','The Influence EP','Curtis|Estrada','Africa Brass Matt Herdman Remix','6/10/2009','Matt Herdman Remix','Electronic - Tech House'),
 (105,'SW034','Curtis|Estrada','The Influence EP','Curtis|Estrada','Africa Brass JJ''s Mamma Dig Mix','6/10/2009','JJ''s Mamma Dig Mix','Electronic - Tech House'),
 (106,'SW034','Curtis|Estrada','The Influence EP','Curtis|Estrada','Pros & Cons','6/10/2009','Original Mix','Electronic - Tech House'),
 (107,'SW034','Curtis|Estrada','The Influence EP','Curtis|Estrada','Pros & Cons Mark Quail Remix','6/10/2009','Mark Quail Remix','Electronic -House'),
 (108,'SW035','My Evil Twiin','The Kaput EP','My Evil Twiin','Kaput','7/15/2009','Original Mix','Electronic - Techno'),
 (109,'SW035','My Evil Twiin','The Kaput EP','My Evil Twiin','Kaput Juan Martos Remix','7/15/2009','Juan Martos Remix','Electronic - Techno'),
 (110,'SW035','My Evil Twiin','The Kaput EP','My Evil Twiin','Fade In','7/15/2009','Original Mix','Electronic - Techno'),
 (111,'SW035','My Evil Twiin','The Kaput EP','My Evil Twiin','One Giant Leap','7/15/2009','Original Mix','Electronic - Techno'),
 (112,'SW036','Rodrigo Diaz','Positive More Negative','Rodrigo Diaz','Positive More Negative','8/12/2009','Original Mix','Electronic - Techno'),
 (113,'SW036','Rodrigo Diaz','Positive More Negative','Rodrigo Diaz','Horns','8/12/2009','Original Mix','Electronic - Techno'),
 (114,'SW036','Rodrigo Diaz','Positive More Negative','Rodrigo Diaz','Ten Seconds','8/12/2009','Original Mix','Electronic - Tech House'),
 (115,'SW037','The Attorney General','Where It Began','The Attorney General','Where It Began','9/9/2009','Original Mix','Electronic - Techno'),
 (116,'SW038','Nerone','The Buzz','Nerone','The Buzz','9/16/2009','Original Mix','Electronic - Techno'),
 (117,'SW038','Nerone','The Buzz','Nerone','The Buzz Pan/Tone Remix','9/16/2009','Pan/Tone Remix','Electronic - Techno'),
 (118,'SW038','Nerone','The Buzz','Nerone','The Buzz Slynus Redux','9/16/2009','Slynus Redux','Electronic - Techno'),
 (119,'SW039','Adam K','Wrong Guru','Adam K','Wrong Guru','9/23/2009','Original Mix','Electronic - Progressive House'),
 (120,'SW040','Neighbors','Hunting Duck EP','Neighbors','Sexual Ship','10/28/2009','Original Mix','Electronic - Techno'),
 (121,'SW040','Neighbors','Hunting Duck EP','Neighbors','Problems','10/28/2009','Original Mix','Electronic - Techno'),
 (122,'SW040','Neighbors','Hunting Duck EP','Neighbors','Hunting Duck','10/28/2009','Original Mix','Electronic - Techno'),
 (123,'SW040','Neighbors','Hunting Duck EP','Neighbors','Airs Dub Mix','10/28/2009','Dub Mix','Electronic - Techno'),
 (124,'SW041','Rodrigo Diaz','Robot Moves EP','Rodrigo Diaz','Robot Moves','12/2/2009','Original Mix','Electronic - Electro-house'),
 (125,'SW041','Rodrigo Diaz','Robot Moves EP','Rodrigo Diaz','Le Fabrique','12/2/2009','Original Mix','Electronic - Techno'),
 (126,'SW041','Rodrigo Diaz','Robot Moves EP','Rodrigo Diaz','Aspire','12/2/2009','Original Mix','Electronic - Techno'),
 (127,'SW042','Hard Rock Sofa','Something From Outside','Hard Rock Sofa','Something From Outside','12/16/2009','Original Mix','Electronic - Tech House'),
 (128,'SW042','Hard Rock Sofa','Something From Outside','Hard Rock Sofa','Something From Outside Greg Kobe Remix','12/16/2009','Greg Kobe Remix','Electronic - Tech House'),
 (129,'SW043','Vitaly Tarasuk','The Aurora EP','Vitaly Tarasuk','The Aurora','1/20/2010','Original Mix','Electronic - Techno'),
 (130,'SW043','Vitaly Tarasuk','The Aurora EP','Vitaly Tarasuk','Go Find','1/20/2010','Original Mix','Electronic - Techno'),
 (131,'SW044','The Attorney General','Secret Weapon Techno Mix Vol. 1','Various','Secret Weapon Techno Mix Vol. 1','2/3/2010','Original Mix','Electronic - Techno'),
 (132,'SW045','Various Artists','Secret Weapon Techno Compilation Vol. 1','Vandermer & Nitin','Beached Beluga','2/3/2010','Original Mix','Electronic - Techno'),
 (133,'SW045','Various Artists','Secret Weapon Techno Compilation Vol. 1','pan/tone','Dirt Bag','2/3/2010','Original Mix','Electronic - Techno'),
 (134,'SW045','Various Artists','Secret Weapon Techno Compilation Vol. 1','Nerone','The Buzz pan/tone Remix','2/3/2010','pan/tone Remix','Electronic - Techno'),
 (135,'SW045','Various Artists','Secret Weapon Techno Compilation Vol. 1','Curtis & Estrada','Doesn''t Matter Nerone Remix','2/3/2010','Nerone Remix','Electronic - Techno'),
 (136,'SW045','Various Artists','Secret Weapon Techno Compilation Vol. 1','Neighbors','Airs Dub Mix','2/3/2010','Dub Mix','Electronic - Techno'),
 (137,'SW045','Various Artists','Secret Weapon Techno Compilation Vol. 1','Rodrigo Diaz','Aspire','2/3/2010','Original Mix','Electronic - Techno'),
 (138,'SW045','Various Artists','Secret Weapon Techno Compilation Vol. 1','Rodrigo Diaz','Ten Seconds','2/3/2010','Original Mix','Electronic - Techno'),
 (139,'SW045','Various Artists','Secret Weapon Techno Compilation Vol. 1','Curtis & Estrada','Africa Brass Matt Herdman Remix','2/3/2010','Matt Herdman Remix','Electronic - Techno'),
 (140,'SW045','Various Artists','Secret Weapon Techno Compilation Vol. 1','German Broadcasters','Activate','2/3/2010','Original Mix','Electronic - Techno'),
 (141,'SW045','Various Artists','Secret Weapon Techno Compilation Vol. 1','Hard Rock Sofa','Something From Outside','2/3/2010','Original Mix','Electronic - Techno'),
 (142,'SW045','Various Artists','Secret Weapon Techno Compilation Vol. 1','Adam K','Wrong Guru','2/3/2010','Original Mix','Electronic - Techno'),
 (143,'SW046','Neighbors','Breake EP','Neighbors','Breake','2/10/2010','Original Mix','Electronic - Techno'),
 (144,'SW046','Neighbors','Breake EP','Neighbors','Extintor','2/10/2010','Original Mix','Electronic - Techno'),
 (145,'SW046','Neighbors','Breake EP','Neighbors','Sadam','2/10/2010','Original Mix','Electronic - Techno'),
 (146,'SW046','Neighbors','Breake EP','Neighbors','Time','2/10/2010','Original Mix','Electronic - Techno'),
 (147,'SW047','Rodrigo Diaz','Jenna & Gretta EP','Rodrigo Diaz','Jenna & Gretta','3/3/2010','Original Mix','Electronic - Tech House'),
 (148,'SW047','Rodrigo Diaz','Jenna & Gretta EP','Rodrigo Diaz','Never Dead','3/3/2010','Original Mix','Electronic - Tech House'),
 (149,'SW048','N-Levy','Loose Knight EP','N-Levy','Loose Knight','3/10/2010','Original Mix','Electronic - Tech House'),
 (150,'SW048','N-Levy','Loose Knight EP','N-Levy','Loose Knight Juan Martos Remix','3/10/2010','Juan Martos Remix','Electronic - Tech House'),
 (151,'SW048','N-Levy','Loose Knight EP','N-Levy','Punch Story','3/10/2010','Original Mix','Electronic - Techno'),
 (152,'SW049','Anton Sever','My Symphony EP','Anton Sever','My Symphony','3/17/2010','Original Mix','Electronic - Tech House'),
 (153,'SW049','Anton Sever','My Symphony EP','Anton Sever','My Symphony Greg Kobe Remix','3/17/2010','Greg Kobe Remix','Electronic - Tech House'),
 (154,'SW049','Anton Sever','My Symphony EP','Anton Sever','My Symphony Max Freegrant Remix','3/17/2010','Max Freegrant Remix','Electronic - Techno'),
 (155,'SW049','Anton Sever','My Symphony EP','Anton Sever','My Symphony Ilya Gushin Remix','3/17/2010','Ilya Gushin Remix','Electronic - Techno'),
 (156,'SW049','Anton Sever','My Symphony EP','Anton Sever','My Symphony Fapples Remix','3/17/2010','Fapples Remix','Electronic - Techno'),
 (157,'SW050','Tony Mafia','Minimal Days EP','Tony Mafia','Minimal Days','4/7/2010','Original Mix','Electronic - Tech House'),
 (158,'SW050','Tony Mafia','Minimal Days EP','Tony Mafia','Minimal Days Alfonso Padilla Remix','4/7/2010','Alfonso Padilla Remix','Electronic - Tech House'),
 (159,'SW050','Tony Mafia','Minimal Days EP','Tony Mafia','Minimal Days Justin James Cass Corridor Take','4/7/2010','Justin James Cass Corridor Take','Electronic - Tech House'),
 (160,'SW050','Tony Mafia','Minimal Days EP','Tony Mafia','Minimal Gods','4/7/2010','Original Mix','Electronic - Techno'),
 (161,'SW050','Tony Mafia','Minimal Days EP','Tony Mafia','Minimal Gods Tony Mafia''s Rech Remix','4/7/2010','Tony Mafia''s Tech Remix','Electronic - Tech House'),
 (162,'SW051','Max Freegrant','When You Smile EP','Max Freegrant','When You Smile','4/21/2010','Original Mix','Electronic - Techno'),
 (163,'SW051','Max Freegrant','When You Smile EP','Max Freegrant','Dead Easter Bunny','4/21/2010','Original Mix','Electronic - Techno'),
 (164,'SW052','Nick da Cruz','Phosphor EP','Nick da Cruz','Phosphor','5/26/2010','Original Mix','Electronic - Techno'),
 (165,'SW052','Nick da Cruz','Phosphor EP','Nick da Cruz','Flourid','5/26/2010','Original Mix','Electronic - Techno'),
 (166,'SW052','Nick da Cruz','Phosphor EP','Nick da Cruz','Sulfat','5/26/2010','Original Mix','Electronic - Techno'),
 (167,'SW052','Nick da Cruz','Phosphor EP','Nick da Cruz','Sulfat Arthur Oskan Lakeshore Rework','5/26/2010','Arthur Oskan Lakeshore Rework','Electronic - Techno'),
 (168,'SW053','Rodrigo Diaz','The Heretic','Rodrigo Diaz','The Heretic','6/16/2010','Original Mix','Electronic - Techno'),
 (169,'SW053','Rodrigo Diaz','The Heretic','Rodrigo Diaz','Magic Place','6/16/2010','Original Mix','Electronic - Tech House'),
 (170,'SW053','Rodrigo Diaz','The Heretic','Rodrigo Diaz','Cross Country','6/16/2010','Original Mix','Electronic - Techno'),
 (171,'SW053','Rodrigo Diaz','The Heretic','Rodrigo Diaz','Porno','6/16/2010','Original Mix','Electronic - Techno'),
 (172,'SW054','Outstrip','Tweak It','Outstrip','Tweak It','6/23/2010','Original Mix','Electronic - Tech House'),
 (173,'SW054','Outstrip','Tweak It','Outstrip','Tweak It Dirty Player Remix','6/23/2010','Dirty Player Remix','Electronic - Tech House'),
 (174,'SW054','Outstrip','Tweak It','Outstrip','Tweak It DJ Chapurin Remix','6/23/2010','DJ Chapurin Remix','Electronic -  Deep House'),
 (175,'SW054','Outstrip','Tweak It','Outstrip','Tweak It Fapples Remix','6/23/2010','Fapples Remix','Electronic - Techno'),
 (176,'SW054','Outstrip','Tweak It','Outstrip','Tweak It Greg Kobe Remix','6/23/2010','Greg Kobe Remix','Electronic - Techno'),
 (177,'SW054','Outstrip','Tweak It','Outstrip','Tweak It Alex Cool Remix','6/23/2010','Alex Cool Remix','Electronic - Tech House'),
 (178,'SW054','Outstrip','Tweak It','Outstrip','Tweak It Ryan Marty Remix','6/23/2010','Ryan Marty Remix','Electronic - Tech House'),
 (179,'SW055','Adam K','Wrong Guru Remixes','Adam K','Wrong Guru Olivier Giacomotto Remix','7/7/2010','Olivier Giacomotto Remix','Electronic -Tech House'),
 (180,'SW055','Adam K','Wrong Guru Remixes','Adam K','Wrong Guru Max Freegrant Remix','7/7/2010','Max Freegrant Remix','Electronic -Tech House'),
 (181,'SW056','Max Freegrant','Dead Easter Bunny Remixes','Max Freegrant','Dead Easter Bunny','4/21/2010','Original Mix','Electronic - Techno'),
 (182,'SW056','Max Freegrant','Dead Easter Bunny Remixes','Max Freegrant','Dead Easter Bunny Adam K Remix','1/17/2011','Adam K Remix','Electronic - Techno'),
 (183,'SW056','Max Freegrant','Dead Easter Bunny Remixes','Max Freegrant','Dead Easter Bunny Serhio Vegas Remix','1/17/2011','Serhio Vegas Remix','Electronic - Tech House'),
 (184,'SW056','Max Freegrant','Dead Easter Bunny Remixes','Max Freegrant','Dead Easter Bunny A.K.O. Remix','1/17/2011','A.K.O. Remix','Electronic - Tech House'),
 (185,'SW056','Max Freegrant','Dead Easter Bunny Remixes','Max Freegrant','Dead Easter Bunny Re-Zone Remix','1/17/2011','Re-Zone Remix','Electronic - Deep House');
